/**
 * Sounds that came from somewhere else, and the manifest that says where.
 *
 * A binding can already point at a built-in or at a file on this machine, and
 * neither of those travels. A config posted in a Discord channel arrives full
 * of `C:\Users\someone\...` — paths that exist on exactly one computer. A pack
 * is the third form: a list of sounds named by URL and pinned by hash, which
 * the tracker fetches once and then keeps by content. Share the config and the
 * sounds follow it.
 *
 * Nothing here fetches anything. This is the reader that meets a manifest
 * somebody wrote by hand and a `packs` block that has been through a text
 * editor — the same job `readSoundSettings` does for the rest, and held to the
 * same rule: a broken field costs that field, never the file. The downloading
 * is `electron/packs.ts`, which is deliberately not trusted with these rules,
 * because it is the half that runs on what a server said.
 *
 * Browser-safe, and its one import is the size ceiling every part of the app
 * enforces, so `node --test` can hold this to every decision below.
 */

import { MAX_SOUND_BYTES } from './sounds.ts';

/** A sound that lives in a pack: `pack:<packId>/<soundId>`. */
export const PACK_PREFIX = 'pack:';

/**
 * What an id may be, and why it is this narrow.
 *
 * A pack id and a sound id are both spliced into a `SoundRef` around a `/`, so
 * an id containing one would parse back as a different pack. They are also the
 * only part of a manifest a person reads out loud. Letters, digits, and the
 * three separators that survive being typed — anything else is a manifest
 * generated by something that should have slugified first.
 */
const ID = /^[a-z0-9][a-z0-9._-]{0,63}$/i;

/** 64 lowercase hex. Anything else is not a SHA-256, whatever it was meant to be. */
const SHA256 = /^[0-9a-f]{64}$/;

/** A manifest is a list of short sounds. One that does not fit here is not that. */
export const MAX_MANIFEST_BYTES = 512 * 1024;

/**
 * How many sounds one pack may name.
 *
 * Not a technical limit — it is what stops a single paste from queueing a
 * thousand requests at somebody's connection, and what keeps the confirmation
 * screen a thing you can read before agreeing to it.
 */
export const MAX_PACK_SOUNDS = 200;

/**
 * Every reason a fetch can end badly, in a form a settings window can translate.
 *
 * Codes rather than sentences, and here rather than beside the code that raises
 * them, because the app speaks three languages: an English string arriving over
 * IPC is one the Russian and Chinese settings windows cannot show. Raised in
 * `electron/packs.ts`, rendered in `src/i18n`.
 */
export type PackFail =
  /** Not an https URL, or a redirect chain that left one. */
  | 'url'
  /** No network, DNS, TLS, or nothing arrived in time. */
  | 'offline'
  /** The server answered, and the answer was not the file. */
  | 'status'
  /** More bytes than the manifest said, or than a notification may be. */
  | 'too-big'
  /** The manifest is not JSON. */
  | 'json'
  /** It is JSON, and it is not a pack — see `readManifest`. */
  | 'shape'
  /** It arrived, and it is not the file the manifest pinned. */
  | 'hash'
  /** It arrived and it is right, and the disk would not take it. */
  | 'write';

/** One sound in a pack: where to get it, and how to know it is the right one. */
export interface PackedSound {
  /** https only. See `readUrl` for why plain http is refused outright. */
  url: string;
  /** Lowercase hex. The file is not accepted, kept, or played unless it hashes to this. */
  sha256: string;
  /** What the file should weigh, so a download can be aborted rather than discovered. */
  bytes: number;
  /** Free text, shown and never enforced — the tracker is not a licence server. */
  license: string;
  /** Who to credit, when the licence asks for it. Null when the manifest said nothing. */
  credit: string | null;
}

/** A named set of them, and the manifest they came from. */
export interface SoundPack {
  id: string;
  /** What to call it in the settings list. */
  name: string;
  /**
   * The manifest URL, or null for a pack assembled by hand.
   *
   * Kept so a pack can be re-read later without the player having to find the
   * link again — and so the settings list can show where a shared config's
   * sounds are actually coming from, which is the question to ask before
   * agreeing to fetch them.
   */
  source: string | null;
  /** Sound id -> where it lives. Never empty: a pack with nothing in it is dropped. */
  sounds: Record<string, PackedSound>;
}

/** What a read threw away, so an install can say so instead of quietly shrinking. */
export interface PackRead {
  pack: SoundPack | null;
  /** Sound ids that did not survive the rules above, in the order they were met. */
  dropped: string[];
}

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

const str = (v: unknown): string | null => (typeof v === 'string' && v !== '' ? v : null);

/**
 * A URL a sound may be fetched from, or null.
 *
 * https only. The hash below would catch a file swapped in transit anyway, so
 * this is not the thing keeping the audio honest — but there is no reason for a
 * manifest to name plain http in the first place, and "the hash will catch it"
 * is a worse answer to give than "we do not fetch those".
 */
function readUrl(raw: unknown): string | null {
  const value = str(raw);
  if (value === null) return null;
  try {
    const url = new URL(value);
    return url.protocol === 'https:' ? url.href : null;
  } catch {
    return null;
  }
}

/** One entry, or null if it is missing anything the fetch cannot proceed without. */
function readSound(raw: unknown): PackedSound | null {
  if (!isRecord(raw)) return null;

  const url = readUrl(raw['url']);
  if (url === null) return null;

  const sha256 = str(raw['sha256'])?.toLowerCase();
  if (sha256 === undefined || !SHA256.test(sha256)) return null;

  const bytes = raw['bytes'];
  /*
   * Required, and this is the one field it would be tempting to make optional.
   * It is what lets a download be aborted at the ceiling instead of at the end
   * of it, and what lets the confirmation screen total the transfer before
   * anybody agrees to it. A manifest that will not say how big its sounds are
   * is one you cannot be shown the cost of.
   */
  if (typeof bytes !== 'number' || !Number.isInteger(bytes) || bytes <= 0 || bytes > MAX_SOUND_BYTES) return null;

  return {
    url,
    sha256,
    bytes,
    // Unknown rather than absent: a blank in the settings list reads as "none
    // needed", and that is a claim this reader is in no position to make.
    license: str(raw['license']) ?? 'unknown',
    credit: str(raw['credit']),
  };
}

/**
 * A pack out of whatever the file holds, and a list of what did not make it.
 *
 * Entry by entry, like every other reader here: one sound with a typo'd hash
 * should not cost the nineteen beside it. A pack left with nothing at all is
 * null, though — an empty pack is a row in the settings list that can never do
 * anything, and it would sit there looking installed.
 */
export function readPack(id: string, raw: unknown, source: string | null): PackRead {
  const dropped: string[] = [];
  if (!ID.test(id) || !isRecord(raw)) return { pack: null, dropped };

  const sounds: Record<string, PackedSound> = {};
  let count = 0;
  if (isRecord(raw['sounds'])) {
    for (const [soundId, entry] of Object.entries(raw['sounds'])) {
      if (count >= MAX_PACK_SOUNDS) {
        dropped.push(soundId);
        continue;
      }
      const sound = ID.test(soundId) ? readSound(entry) : null;
      if (sound === null) {
        dropped.push(soundId);
        continue;
      }
      sounds[soundId] = sound;
      count++;
    }
  }
  if (count === 0) return { pack: null, dropped };

  return {
    pack: { id, name: str(raw['name']) ?? id, source: readUrl(source), sounds },
    dropped,
  };
}

/**
 * The `packs` block of a config file.
 *
 * The id is the key, not a field, so a hand edit cannot produce two packs that
 * disagree about which one they are. A pack that fails the rules is dropped
 * whole and silently — this runs on every launch, and a config file is not a
 * place to report errors to somebody who is not looking.
 */
export function readPacks(raw: unknown): Record<string, SoundPack> {
  if (!isRecord(raw)) return {};
  const packs: Record<string, SoundPack> = {};
  for (const [id, entry] of Object.entries(raw)) {
    const source = isRecord(entry) ? entry['source'] : null;
    const { pack } = readPack(id, entry, typeof source === 'string' ? source : null);
    if (pack) packs[id] = pack;
  }
  return packs;
}

/** A name into something that can be an id: lowercase, and only what `ID` allows. */
function slug(value: string): string | null {
  const out = value
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^[^a-z0-9]+/, '')
    .slice(0, 64)
    .replace(/[-._]+$/, '');
  return ID.test(out) ? out : null;
}

/**
 * A fetched manifest, which unlike a config block has to name itself.
 *
 * Three tries at an id, in the order of who meant it: the manifest's own `id`,
 * then its display name, then the host it came from. The last is a poor id and
 * a fine fallback — it is stable, it will not collide with a pack from anywhere
 * else, and the player sees it before they agree to anything.
 */
export function readManifest(raw: unknown, source: string): PackRead {
  const declared = isRecord(raw) ? raw : {};
  const host = (() => {
    try {
      return new URL(source).hostname;
    } catch {
      return '';
    }
  })();

  const named = str(declared['id']);
  const titled = str(declared['name']);
  const id = (named && slug(named)) || (titled && slug(titled)) || slug(host);
  if (!id) return { pack: null, dropped: [] };
  return readPack(id, declared, source);
}

/** True for a reference into a pack rather than a built-in or a path. */
export const isPack = (ref: string): boolean => ref.startsWith(PACK_PREFIX);

/** `pack:jackpots/vine-boom`. The one place the two ids are joined. */
export const packRef = (packId: string, soundId: string): string => `${PACK_PREFIX}${packId}/${soundId}`;

/**
 * And the one place they are taken apart.
 *
 * Split on the first `/` only, even though `ID` forbids one on either side:
 * this parses references out of a config file, where the rules were a
 * suggestion, and what it returns is looked up in a map that only holds ids
 * which passed them. A wrong answer here is a miss, not a mispoint.
 */
export function parsePackRef(ref: string): { pack: string; sound: string } | null {
  if (!isPack(ref)) return null;
  const rest = ref.slice(PACK_PREFIX.length);
  const slash = rest.indexOf('/');
  if (slash <= 0 || slash === rest.length - 1) return null;
  return { pack: rest.slice(0, slash), sound: rest.slice(slash + 1) };
}

/** The entry a reference points at, or null if the pack or the sound is gone. */
export function packedSound(packs: Record<string, SoundPack>, ref: string): PackedSound | null {
  const parsed = parsePackRef(ref);
  if (parsed === null) return null;
  return packs[parsed.pack]?.sounds[parsed.sound] ?? null;
}

/**
 * Every hash the installed packs still refer to.
 *
 * The store is keyed by content, so two packs naming the same file share one
 * copy on disk — which means nothing may be deleted because *a* pack was
 * removed, only because *no* pack still wants it. This is that set.
 */
export function referencedHashes(packs: Record<string, SoundPack>): Set<string> {
  const hashes = new Set<string>();
  for (const pack of Object.values(packs)) {
    for (const sound of Object.values(pack.sounds)) hashes.add(sound.sha256);
  }
  return hashes;
}

/**
 * The pack imported sounds land in.
 *
 * One pack rather than one per sound, because a pack is the unit a config
 * carries and twenty packs of one sound each would be twenty headings in the
 * picker. Its `source` is null: nothing can re-read it, since it was assembled
 * here out of individual choices rather than fetched from a manifest.
 */
export const IMPORTED_PACK = 'freesound';

/**
 * What an imported sound is called inside that pack.
 *
 * The catalogue's own id is on the end, and it is doing the work: two sounds
 * genuinely called "coin" are two entries, and importing the same one twice
 * lands on the same id and replaces rather than duplicates. The name in front
 * is so the picker shows `coin-drop-411642` and not a bare number — a list of
 * ids is a list you cannot choose from.
 */
export function importedSoundId(name: string, catalogueId: number): string {
  const stem = slug(name)?.slice(0, 40).replace(/[-._]+$/, '');
  return stem ? `${stem}-${catalogueId}` : String(catalogueId);
}
